### ISSUE TITLE
Update Cosmic ?

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/CAW#349] opened 2017-05-11 08:45 UTC
COSMIC made a new release: v81
Should we update?

**Comment by MaxUlysse** [comment] 2017-05-15 10:05
Asked to UPPMAX, so we can probably close this issue.

**Comment by szilvajuhos** [comment] 2017-06-28 07:23
Duplicate of #204 , closing.

**Closed by szilvajuhos** 2017-06-28 07:23 UTC
Labels: question
